# Pandas - Online Retail

In [4]:
import pandas as pd
import numpy as np

In [3]:
# Excel
# data_excel = pd.read_excel(path)
# JSON
# data_json = pd.read_json(path)

path = "./datasets/Online_Retail.csv"
sales_data = pd.read_csv(path, encoding='latin-1')

print(type(sales_data))
print(sales_data.head())

<class 'pandas.core.frame.DataFrame'>
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
1    536365     71053                  WHITE METAL LANTERN         6
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6

    InvoiceDate  UnitPrice  CustomerID         Country
0  12/1/10 8:26       2.55     17850.0  United Kingdom
1  12/1/10 8:26       3.39     17850.0  United Kingdom
2  12/1/10 8:26       2.75     17850.0  United Kingdom
3  12/1/10 8:26       3.39     17850.0  United Kingdom
4  12/1/10 8:26       3.39     17850.0  United Kingdom

In [ ]:
# creación de datafreme apartir de datos sencillos
data = np.arange(1,10).reshape(3,3)
dt_from_array = pd.DataFrame(data, columns=['A','B','C'])
print(dt_from_array)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

## Creación de Dataframe desde una lista

In [8]:
data = [[1,'Fabian', 39], [2, 'Ana', 24], [3, 'LP', 42]]
data_from_list = pd.DataFrame(data, columns=["ID", 'Name', 'Age'])
data_from_list.head()

   ID    Name  Age
0   1  Fabian   39
1   2     Ana   24
2   3      LP   42

## Creación de DataFrame desde un diccionario

In [10]:
data = [{'ID': 1, 'Name': 'José', 'Age': 38}, {'ID': 2, 'Name': 'María', 'Age': 8}]
dt_from_dict_list = pd.DataFrame(data)
print(dt_from_dict_list)
dt_from_dict_list.head()

   ID   Name  Age
0   1   José   38
1   2  María    8

   ID   Name  Age
0   1   José   38
1   2  María    8

In [13]:
data = {'Id':[1,2,3,4], 'Name':['Ana','Migue','Fabian','Guillermo'], 'Age':[32,23,43,21]}
dt_from_dict = pd.DataFrame(data)
dt_from_dict.head()

   Id       Name  Age
0   1        Ana   32
1   2      Migue   23
2   3     Fabian   43
3   4  Guillermo   21

Series

In [14]:
data = {'ID': pd.Series([1,2,3,4]),
        'Name': pd.Series(['Ana','Migue','Fabian','Guillermo']),
        'Age': pd.Series([32,23,43,21])}
df_from_series_dict = pd.DataFrame(data)
df_from_series_dict.head()

   ID       Name  Age
0   1        Ana   32
1   2      Migue   23
2   3     Fabian   43
3   4  Guillermo   21