## Datos faltantes - Datos Nulos
Existen 2 formas de verificar si los datos están o no. Pandas maneja 2, si el dato está disponible o si es nulo.

In [2]:
import pandas as pd

In [4]:
path = "./datasets/Online_Retail.csv"
retail_data = pd.read_csv(path, encoding='latin-1')
retail_data.head(2)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom

In [6]:
missing_data =  retail_data.isna()
missing_data.head(4)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False

## Contar de cada columna cuantos datos faltan